name: Label List PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: local
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: other
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: local/tools/requirements.txt
      - run: pip install dnspython
      - run: python local/tools/check_dns.py local/data.txt other/data.txt ${{ github.event.pull_request.number }}